### ISSUE TITLE
Can I pay your attention?

### ISSUE THREAD

**Issue by kuckboy1994** [JCarlosR/teresa#1]
hello guys, I am very glad to see you using my components that is called simpleTimer.js in your project,but for some reasons,I must to delete some records that i had issued. So can you delete the line contain email address in "teresa/public/themes/archi/js/simpletimer.js"  file, Thank you !

**Comment by JCarlosR** [comment]
Hi @kuckboy1994 
I have deleted the email address at https://github.com/JCarlosR/teresa/blob/master/public/themes/archi/js/simpletimer.js
We can still use simpleTimer, right?
Thanks.

**Comment by kuckboy1994** [comment]
of course, thank you anyway. 😊
